# Server port
server:
  port: 8080

api-version: V0.1
url-configuration:
  baseUrl: http://localhost:8080/

# Spring Data Source Configuration
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/local_application_db
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    database-platform: org.hibernate.dialect.MySQL57Dialect

